### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_Locast#141]
```
# docker build --tag fhdhr_locast:0.4.6 .
FROM ghcr.io/linuxserver/baseimage-ubuntu:focal

# set version label
ARG BUILD_DATE
ARG VERSION
ARG FHDHR_LOCAST_RELEASE
ARG DEBIAN_FRONTEND="noninteractive"
  
RUN apt-get -qq update && \
    apt-get -qq -y install ffmpeg vlc gcc python3-pip && \
    apt-get autoclean

COPY ./ /app/
WORKDIR /app
RUN pip3 install -r requirements.txt

RUN apt-get -qq update && \
    apt-get -qq -y remove gcc && \
    apt-get autoclean

EXPOSE 1900 5004
VOLUME /app/config
ENTRYPOINT ["python3", "/app/main.py", "--config", "/app/config/config.ini"]

```

**Comment by deathbybandaid** [comment]
What am I lookng at? What's the issue

**Comment by deathbybandaid** [comment]
@Berserkir-Wolf any idea what I'm lookng at? He's posted the same 'issue' in multiple varients

**Comment by deathbybandaid** [comment]
Also, ffmpeg is no longer a requirement, but an option. Also, VLC is an option for streaming.

Either we include both, or neither?

**Comment by Protektor-Desura** [comment]
That is how I built the docker image and shows that I am using the Linux Server/Ubuntu 20.02 (Focal) as the base.

**Comment by Protektor-Desura** [comment]
I included both options (VLC & ffmpeg) so users wouldn't have to adjust the image, they could just pick whatever they wanted to use.

**Comment by deathbybandaid** [comment]
Shoulnt these be PRs, and not issues?

**Comment by Protektor-Desura** [comment]
I wasn't sure if you wanted to edit anything or not, figured you could discuss it easier this way, but I can do a PR for them.

**Comment by Protektor-Desura** [comment]
Docker Compose is more a documentation thing than a PR.

**Comment by deathbybandaid** [comment]
@Berserkir-Wolf is going to help me out with some docker stuff, and publish images on dockerhub and whatnot.

I'm not a docker person
