### ISSUE TITLE
Connection Closing

### ISSUE THREAD

**Issue by jgomez177** [fHDHR/fHDHR_Locast#183]
When viewing a channel, after about 5-10 minutes stream ends with the following:

```
fHDHR - INFO - Connection Closed: <urlopen error [Errno 104] Connection reset by peer>
fHDHR - INFO - Connection Closed: Tuner Lock Removed
fHDHR - INFO - Tuner #0 Released.

```

Happens when view from iOS or AppleTV client and in Emby, Channels DVR or Plex

**Comment by deathbybandaid** [comment]
Connection reset by peer would seem to something on Locasts server cutting you off.

Just to verify, have you donated to Locast?

**Comment by jgomez177** [comment]
Yes:

`
fHDHR - INFO - User donationExpire: 2021-02-28 08:39:04
`

**Comment by tharris9d** [comment]
After seeing this issue I started testing the latest update. I haven't been able to get through ANY show on Plex without it losing the connection. I tried Dr Phil and was kicked after 4 minutes. I tried Highway to heaven and was kicked out after 16 minutes. I tested in the Windows app and got booted again from Highway to Heaven after 7 minutes. I also noticed the sound off just a bit when it hit the ads in Plex. I am running on Spectrum 1gb internet.

**Comment by deathbybandaid** [comment]
You can try setting the method to ffmpeg (and have that in your PATH)

**Comment by jgomez177** [comment]
setting the stream_type to ffmpeg and the bytes_per_read to 1152000 appears to have resolved the problem.

Thanks!

**Comment by deathbybandaid** [comment]
I'm on the direct method testing and over a half hour

**Comment by deathbybandaid** [comment]
Passed an hour, Not seeing this issue.

Commercials are part of the stream and wouldn't effect the audio delay.

It's entirely possible that Locasts servers wer having issues prior to me having a chance to test.

**Comment by jgomez177** [comment]
Not sure either but given I'm working with ffmpeg I'm fine with having this workaround in place. I can try going back to direct at a later time
