### ISSUE TITLE
Guide from xmltv is 5 hour ahead in Los Angeles

### ISSUE THREAD

**Issue by tharris9d** [fHDHR/fHDHR_Locast#42]
The guide is pulling in the Los Angeles info but it's 5 hours ahead. Is there something I can put in the config to adjust for the time? It was working fine a few versions ago. Locast2Plex is pulling in the correct time.
![TimeZoneIssue](https://user-images.githubusercontent.com/217445/96212845-863c2b80-0f2c-11eb-95a6-f9e5a82e204b.PNG)
Any tips to get this working either via config or other would be appreciated. See screenshot attached.

**Comment by deathbybandaid** [comment]
#43 may fix this for you.

Prior to this fix, it would have automatically retrieved for the timezone it detects you in. It should now force UTC.

**Comment by tharris9d** [comment]
@deathbybandaid It looks like fHDHR_locast works fine by itself. The issue is in the xmltv file generated to use with xteve using 127.0.0.1:5004/xmltv.xml.
[xmltv_run9_21amPST_10_16_2020.xml.txt](https://github.com/fHDHR/fHDHR_Locast/files/5393010/xmltv_run9_21amPST_10_16_2020.xml.txt)

 The data doesn't match the guide. I attached an xmltv file generated at 9:21am on 10_16 and it has data from 10_15 in it. I even deleted the cache, refreshed Plex guide before running this. The Plex Guide was accurate. Shouldn't the xmltv file match the guide to use in xteve? Maybe I am doing this wrong. Let me know.

**Comment by deathbybandaid** [comment]
that seems like an issue with xteve,,, I'm using mine directly into plex

**Comment by deathbybandaid** [comment]
WAIT,,,,,

so if I understand correctly,,,,

fHDHR_Locast and fHDHR_PlutoTV are connected to your xteve as either m3u or hdhr under "Playlists".

Under "xmltv" you have these ip:port/xmltv.xml as guides.

Under "mapping" you have the channels mapped to the correct guide information from the fHDHR xmltv.

You then have Plex/emby/jellyfin connected to xteve.

Plex will have it's own xmltv cache, but under "xmltv" in xteve, you need to update from there as well.

**Comment by tharris9d** [comment]
Correct to the above
I updated from xteve but seem to get the same old xmltv file. If I run the Web UI xmltv I get don't seem to get an update. I ran them each day but no change.
**I decided to try Zap2xml.pl separately, ran it with my zipcode and timezone set to PT. I then removed 127.0.0.1:5004/xmltv.xml from xteve and added the path to the xmltv file generated by Zap2xml and it worked perfectly. I mapped the locast files to zap2xml and the pluto files to your fHDHR_Pluto xmltv mapping and now I have it all working.** I'm not sure why the Locast xmltv file isn't working. I played with the code but didn't have any luck....yet.

**Comment by deathbybandaid** [comment]
So here's what you need to do,

Verify you have up to date master cloned,

Clear your cache folder

Update xmltv in xteve,

Update xmltv in plex

**Comment by deathbybandaid** [comment]
Additionally as per the wiki

![Screenshot_20201016-195036_Firefox](https://user-images.githubusercontent.com/18010545/96322904-f01a0b00-0fe8-11eb-9d25-f07f1d55c16f.jpg)


zap2it is a valid EPG method for fHDHR_Locast, already built in.

**Comment by deathbybandaid** [comment]
You can also try removing the DVR from plex, restart the plexmediaserver service, and then readd xteve as a Hdhr and add the xmltv from xteve into plex
