### ISSUE TITLE
occasional 500 error on web UI streams page

### ISSUE THREAD

**Issue by crackers8199** [fHDHR/fHDHR_Locast#65]
this happens occasionally, but i haven't been able to come up with a definitive way to always reproduce it. seems random.

doesn't seem to affect the actual streams at all (still able to load streams just fine from within channels dvr which is what i'm feeding with this), and the debug page still shows which tuners are active...just the actual streams page gives a 500 error when this happens.

will see if there is any data in the logs next time i see this and add them here.

**Comment by deathbybandaid** [comment]
Closing this issue, the error was related to EPG not being loaded properly, and there is now error handling for this.
