### ISSUE TITLE
remote end closed connection without response

### ISSUE THREAD

**Issue by crackers8199** [fHDHR/fHDHR_Locast#66]
watching a channel, stream just randomly stopped out of nowhere. checked the logs and found this:

```
fHDHR - INFO - Connection Closed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
fHDHR - INFO - Tuner #2 Released.
```

seems this might be an issue with locast disconnecting the stream when using direct. just re-started to see if the same thing happens again and if i can get it to happen reliably...will update as details warrant.

**Comment by crackers8199** [comment]
i've had the same stream on now for over an hour and a half since restarting it after this happened, and it hasn't happened again. i wonder if it's somehow related to #64 and will only happen on the first stream after booting the docker container. will investigate further later today.

**Comment by deathbybandaid** [comment]
This doesn't seem to be an issue with fHDHR, and seems like you were cut off from Locast directly.

Did you happen to have multiple concurrent streams from Locast? (in your primary Channels, your test Channels, Locast app)

Per their documentation, you can have 4 streams, and switching channels can cause you issue, so fHDHR sets the tuner limit to 3.

**Comment by crackers8199** [comment]
> This doesn't seem to be an issue with fHDHR, and seems like you were cut off from Locast directly.
> 
> Did you happen to have multiple concurrent streams from Locast? (in your primary Channels, your test Channels, Locast app)
> 
> Per their documentation, you can have 4 streams, and switching channels can cause you issue, so fHDHR sets the tuner limit to 3.

nope, i only had one at the time.

i have the tuner count set to 6, as i've found them to be pretty lax enforcing that 4 stream rule and wanted to avoid issues with my wife and i both changing channels (hence the two extra tuners on top of the four they allow). YMMV, of course.

**Comment by deathbybandaid** [comment]
Closing until reproduced
