### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DeadBadger86** [fHDHR/fHDHR_Locast#75]
Script fails to start with error:

```
python3 main.py -c=config.ini
Loading fHDHR v0.4.0-beta
Loading Configuration File: config.ini
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 98, in main
    return start(args, script_dir)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 88, in start
    return run(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 42, in run
    fhdhr = fHDHR_OBJ(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/__init__.py", line 29, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/__init__.py", line 14, in __init__
    self.channels = Channels(fhdhr, origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 43, in __init__
    self.get_channels()
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 68, in get_channels
    channel_dict_list = self.origin.get_channels()
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/origin/__init__.py", line 55, in get_channels
    return self.channels.get_channels()
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/origin/origin_channels.py", line 35, in get_channels
    "callsign": str(station_item['callSign']).split(" ")[1],
IndexError: list index out of range
```

**Comment by deathbybandaid** [comment]
What DMA?

**Comment by deathbybandaid** [comment]
I can patch this first thing tomorrow morning

**Comment by deathbybandaid** [comment]
Or maybe right now

**Comment by DeadBadger86** [comment]
If I hardcode the sub-object in question and print the station_items in ./origin/origin_channel.py, I get:

`{'id': 1059, 'dma': 725, 'stationId': '35471', 'name': 'KTTWDT', 'callSign': 'KTTW', 'logoUrl': 'https://static.locastnet.org/logo/SiouxFalls/KTTW.png', 'active': True, 'listings': [{'stationId': 1059, 'startTime': 1605488400000, 'duration': 1860, 'isNew': True, 'audioProperties': 'CC, DD 5.1, DVS, HD 720p, New, Stereo', 'videoProperties': 'CC, DD 5.1, DVS, HD 720p, New, Stereo', 'rating': 'TVPG', 'programId': 'EP000186930736', 'title': 'The Simpsons', 'description': 'Grampa is accused of a crime; Kent Brockman questions his career.', 'entityType': 'Episode', 'airdate': 1605398400000, 'genres': 'Sitcom, Animated', 'episodeTitle': 'Podcast News', 'showType': 'Series', 'hasImageArtwork': False, 'hasSeriesArtwork': False, 'preferredImage': 'https://fans.tmsimg.com/assets/p18722572_b_v5_ac.jpg', 'preferredImageWidth': 240, 'preferredImageHeight': 360, 'topCast': 'Dan Castellaneta, Julie Kavner, Nancy Cartwright', 'seasonNumber': 32, 'episodeNumber': 6, 'shortDescription': 'Grampa is accused of a crime; Kent Brockman questions his career.', 'releaseYear': 2020, 'releaseDate': 1605398400000, 'seriesId': '183872'},`


Looks like DMA 725?

**Comment by DeadBadger86** [comment]
Take that output with a grain of salt. My python is trash.

**Comment by deathbybandaid** [comment]
That's very helpful actually,, most stations I've seen from locast have the callsign as:

````
{"id":104,"dma":501,"stationId":"16689","name":"WCBSDT","callSign":"2.1 CBS"
````

So this is odder than I anticipated, as the `callSign` should include the channel number as well.

**Comment by deathbybandaid** [comment]
I'll have to attack this fresh in the morning, it looks like none of your channels include channel numbers via the Locast API.

**Comment by DeadBadger86** [comment]
Yeah, I was wondering if it was some kind of global API change or just the data in this DMA.  Let me know if you need me to test anything.

**Comment by deathbybandaid** [comment]
@DeadBadger86 this is what DMA 501 looks like:

https://api.locastnet.org/api/watch/epg/501

**Comment by deathbybandaid** [comment]
I may have something for you to test in a few minutes

**Comment by DeadBadger86** [comment]
Why am I not surprised that the most rural DMA doesn't have the same data as everywhere else... Sigh.

**Comment by DeadBadger86** [comment]
I'll be here.  Thanks for looking at this.  I assume it's a far edge case.

**Comment by deathbybandaid** [comment]
@DeadBadger86 

https://github.com/deathbybandaid/fHDHR_Locast/tree/dev

I just pushed something for you to test, very interesting issue you found!

**Comment by DeadBadger86** [comment]
Different error now:

```
python3 main.py -c=config.ini
Loading fHDHR v0.4.0-beta
Loading Configuration File: config.ini
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 98, in main
    return start(args, script_dir)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 88, in start
    return run(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 42, in run
    fhdhr = fHDHR_OBJ(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/__init__.py", line 29, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/__init__.py", line 14, in __init__
    self.channels = Channels(fhdhr, origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 43, in __init__
    self.get_channels()
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 69, in get_channels
    channel_dict_list = self.verify_channel_info(channel_dict_list)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 137, in verify_channel_info
    station_item["number"] = str(float(station_item["number"]))
ValueError: could not convert string to float: 'KTTW'
```

**Comment by DeadBadger86** [comment]
```
 git status
On branch dev
Your branch is up to date with 'origin/dev'.
```

**Comment by deathbybandaid** [comment]
Okay, I'll go sleep, and get at this in the morning, I thought I could whip something out quick before bed.

**Comment by DeadBadger86** [comment]
Sounds good.  Thanks again,

**Comment by deathbybandaid** [comment]
@DeadBadger86 back to this repo, the following push should alleviate your issue:

https://github.com/fHDHR/fHDHR_Locast/pull/76

Note: this generates a channel number on the fly, so it won't match your local channel numbers.

I'm working on a solution to manage the channel numbers via the webUI, but for now I'd recommend checking out xteve to remap the channel numbers (if that's important for you)

**Comment by DeadBadger86** [comment]
It looks like it got through the first channel this time but gets stuck on the second:

```
python3 main.py -c=config.ini
Loading fHDHR v0.4.0-beta
Loading Configuration File: config.ini
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    sys.exit(run.main(SCRIPT_DIR))
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 107, in main
    return start(args, script_dir)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 97, in start
    return run(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/cli/run.py", line 43, in run
    fhdhr = fHDHR_OBJ(settings, logger, db)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/__init__.py", line 29, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/__init__.py", line 14, in __init__
    self.channels = Channels(fhdhr, origin)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 43, in __init__
    self.get_channels()
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 69, in get_channels
    channel_dict_list = self.verify_channel_info(channel_dict_list)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/channels.py", line 137, in verify_channel_info
    station_item["number"] = str(float(station_item["number"]))
ValueError: could not convert string to float: 'PBS'
```

**Comment by deathbybandaid** [comment]
Just to verify, you are on the most recent fHDHR/fHDHR_Locast Master?

**Comment by deathbybandaid** [comment]
I only ask because if the `callSign` given in the Locast API doesn't have a number, the script shouldn't even pass a `number` key to the channels wrapper

**Comment by DeadBadger86** [comment]
Yes, I deleted my local copy of your dev fork and re-cloned from master:

```
git rev-parse --short HEAD
6dec15a
```

**Comment by deathbybandaid** [comment]
I see the problem now, the "PBS Kids" has a space in the name.

**Comment by DeadBadger86** [comment]
Ah, that makes sense.  So it gets to that one, splits on the space and assumes the first value is the channel number.  Then, proceeds to puke when it tries to convert "PBS" to a float?

**Comment by deathbybandaid** [comment]
correct, I'm not writing some logic to determine if the first space split is an `int` or a `float`

**Comment by deathbybandaid** [comment]
@DeadBadger86 want to give my dev branch a try?

**Comment by deathbybandaid** [comment]
in case you already pulled and tried, I just did another push for the EPG side of things

**Comment by DeadBadger86** [comment]
That's more progress.  There's still an error, but it looks like it got far enough through the initial setup to stay running: 

python3 main.py -c=config.ini
Loading fHDHR v0.4.0-beta
Loading Configuration File: config.ini
HTTP Server Starting
SSDP Server Starting
EPG Update Starting
fHDHR - ERROR - Error with Received packet from ('10.<output omitted>seemingly harmless error from my harmony hub making a bad request</output omitted>
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/epg.py", line 167, in run
    self.update(epg_method)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/epg.py", line 146, in update
    programguide = func_to_call(self.channels)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/origin/__init__.py", line 61, in update_epg
    return self.epg.update_epg(channels)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/origin/origin_epg.py", line 38, in update_epg
    channel_number = fhdhr_channels.get_channel_dict(self, "callsign", channel_callsign)
TypeError: get_channel_dict() takes 3 positional arguments but 4 were given

**Comment by deathbybandaid** [comment]
@DeadBadger86 try again,,

what's nice is dumb stuff like this gets squashed before going to fhdhr/master

**Comment by DeadBadger86** [comment]
New error.  Still stays running.

```
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/epg.py", line 167, in run
    self.update(epg_method)
  File "/opt/fhdhr/fHDHR_Locast/fHDHR/device/epg.py", line 151, in update
    floatnum = str(float(chan))
ValueError: could not convert string to float: "{'name': 'KTTWDT', 'id': 1059, 'callsign': 'KTTW', 'tags': [], 'number': '17.0'}"
```

Agreed.  Again, really appreciate the time and effort on this.

**Comment by deathbybandaid** [comment]
ah, I see the issue!

**Comment by deathbybandaid** [comment]
@DeadBadger86 how about now?

**Comment by DeadBadger86** [comment]
That's it!  It's running, no errors on start.  I can see guide info from the WebUI and all of the channels appear to be present.  I have an xTeVe docker container running to remap the channel numbers and merge my other m3u8 sources before they hit Plex.

**Comment by deathbybandaid** [comment]
Sweet, I'll squash, and merge into this repo, so you can get off of my dev branch

**Comment by deathbybandaid** [comment]
Pushed, and closing this issue!
