### ISSUE TITLE
fHDHR_Locast Guide is only correct if I force OS timezone to UTC

### ISSUE THREAD

**Issue by Neotribal** [fHDHR/fHDHR_Locast#90]
Running fHDHR_Locast on a Raspberry Pi... the fHDHR Guide (http://x.x.x.x:5004/guide) only works correctly if I force the rPI's timezone to UTC... If I try to set my actual timezone ("timedatectl set-timezone America/New_York", aka EST, -5:00), the guide programming incorrectly shifts 5 hours forward. (eg: at 2PM EST the guide shows 7PM EST programming, i.e. "Local News @ 7pm"). 

Cleared out the xmltv locast cache and re-updated it, no change. Tried blowing out the entire fHDHR_Locast directory, rebooting, re-cloning/pulling from git with a fresh barebones config.ini just now to make sure I have https://github.com/fHDHR/fHDHR_Locast/pull/43... same result.

**Comment by deathbybandaid** [comment]
I'm eastern time, and have no issue with my Locast data.

The api URL pulled for EPG is:

`https://api.locastnet.org/api/watch/epg/` YOUR DMA NUMBER `?startTime=`

The start time would look like this:

`2020-11-23T002020-11-23T00%3A00%3A00-00%3A00A00%3A00-00%3A00`

YYYY-MM-DD, Midnight. fHDHR intentionally uses UTC in the request to Locast's servers and your local time SHOULD have nothing to do with the request of data. the guide data saved in the database, as well as the xmltv is stored in UTC.

**Comment by deathbybandaid** [comment]
I just double checked, the guide from fHDHR matches what I see in Plex, and evening news and Morning news shows are at their correct timeslots.

**Comment by deathbybandaid** [comment]
You can also look at the built-in Zap2it guide information (force an update on that), and see if that is also mis-aligned.

**Comment by deathbybandaid** [comment]
Also doublechecked the first timestamp available in the requested API:

`1606089600000` and using https://www.epochconverter.com/ I found that the timestamp is for midnight GMT, which is accurate

**Comment by Neotribal** [comment]
Only seems to be affecting my origin guide,  Zap2it guide info seems to work fine regardless of the local timezone, haven't tested blocks. No clue why the local timezone would be involved at all, since you deliberately reference of UTC... 

I enabled debug logging in config.ini while troubleshooting earlier but saw nothing unusual from fHDHR. UTC was reporting correctly while it was misbehaving. Spent a couple of hours poking and prodding... immediately started working as soon as I switched the timezone.

Might just be something janky on this device's os install... I'll try setting my timezone back to EST in the morning and report back

**Comment by deathbybandaid** [comment]
I have an old odroid that gave me time issues, so anything is possible

**Comment by deathbybandaid** [comment]
any update on this? (I try not to leave too many open issues, as it slows my development of new features)

**Comment by Neotribal** [comment]
Took me a while to get back to this... sorry about that. Changed my timezone back to EST and the guide is working fine. Must have been a momentary issue on my end.

**Comment by deathbybandaid** [comment]
Awesome, closing the issue
