### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by 2IkHLHB** [fHDHR/fHDHR_Locast#98]
I find your project very interesting, especially since the project locast2plex is very unstable to me, breaks a lot, on a good amount of people.
My question, would be possible to host this project on Docker Hub?(https://hub.docker.com) The reason, myself, as well as many other individuals, do not have the tools / environment to build the docker container via git (In my case, running a Synology NAS)
Just wondering if said option is possible. Thank you in advance.

**Comment by deathbybandaid** [comment]
I'm not a docker user, but there is an open PR for this exact thing.

I just need to take the time to figure out what I have to do exactly to make it work

**Comment by 2IkHLHB** [comment]
Awesome...
Thank you in advance for taking this option into consideration and, hopefully, you can make this work. That way, this project can be exposed to people with less experience with Docker. Best of luck.
